version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-3371
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - test_3371-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettotest/camunda-local:april2020
    container_name: camunda-3371
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy
    container_name: authproxy-3371
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice
    container_name: camundasvc-3371
    ports:
      - "0000:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager
    container_name: securitymanager-3371
    ports:
      - "0000:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway
    container_name: apigateway-3371
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - test



  test: 
    build: ../../../application/services/custom_services/test
    image: test-3371
    container_name: test-3371
    ports: 
      - 8014:8014
    env_file: .env
    depends_on:
      - mongo


volumes:
  test_3371-volume:
    driver: local
